# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fc58835ac07b26792e4930ef247084d5b3a48b0116ad26c2d642093315361dca5237ced6e5ff9c22a50a003759633fb684211df2a0614222313c7d7daf192cb

test:
  secret_key_base: ae8fe7ac0b1d2e4339f27f436966e48d232c60f406801997fe6a75d819b3f5f6a6cb91979c0f0de9714d0d6d429ee22d886c1b184f0bf645d192eba8a213b940

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
